stages:
  - build
  - build-docker-image
  - push-image-to-docker-hub
  - new-relic-exporter

build-docker-image:
  stage: build-docker-image
  script:
    - docker info
    - docker build -t ihappysoni/blognodeapp .

Push Docker Image to DockerHub:
  stage: push-image-to-docker-hub
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker info
    - docker push ihappysoni/blognodeapp
    - echo "Done"

new-relic-exporter:
  stage: new-relic-exporter
  inherit:
   variables: true
  variables:
   CI_PARENT_PIPELINE: $CI_PIPELINE_ID
  trigger:
   include:
     - local: new-relic-exporter.yml