name: Node.js App Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Start app
      run: npm start &
      
    - name: Wait for app to start
      run: |
        for i in {1..10}; do
          curl -s http://localhost:4000 >/dev/null && break
          sleep 1
        done
      
    - name: Run tests
      run: npm test
