name: Retrieve Github Repository Events

on:
  push:
    branches:
      - main

env:
  OWNER: ihappysoni
  REPO: https://github.com/ihappysoni/BlogAppNode
  TOKEN: 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

jobs:
  retrieve-events:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Retrieve Github Repository Events
      run: |
         curl -H "Authorization: token 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" https://api.github.com/repos/ihappysoni/BlogAppNode/events
      
    

    - name: Annotation  
      run: |
         curl -H "Authorization: token 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" https://api.github.com/repos/ihappysoni/BlogAppNode/issues/#1/timeline
    


    - name: Checkout code
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{repo}/actions/runs/{run_id}/jobs
        repo: ${{ github.repository }}
        run_id: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  

    - name: Check-Run
      run: |
        curl \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer 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"\
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/ihappysoni/BlogAppNode/check-runs/{run_id}   