name: Example Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send metrics to New Relic
      run: |
        curl -vvv -k -H "Content-Type: application/json" \
        -H "Api-Key: NRAK-0EZO21RRJYYZDN6J7G0LI2F8YK9" \
        -X POST https://metric-api.newrelic.com/metric/v1 \
        --data '[{ 
            "metrics":[{ 
                "name":"memory.heap", 
                "type":"gauge", 
                "value":2.3, 
                "timestamp":CURRENT_TIME, 
                "attributes":{"host.name":"dev.server.com"} 
            }] 
        }]'
    - name: Programmatically retrieve NrIntegrationError events
      run: |
        curl -H "Accept: application/json" -H "X-Query-Key:NRAK-0EZO21RRJYYZDN6J7G0LI2F8YK9" "https://insights-api.newrelic.com/v1/accounts/3660048/query?nrql=SELECT%20*%20FROM%20NrIntegrationError%20where%20newRelicFeature='Metrics'"    


 