name: Example Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send metrics to New Relic
      run: |
        curl -vvv -k -H "Content-Type: application/json" \
        -H "Api-Key: 8be23cc655a1111a98e81e6835cf000aFFFFNRAL" \
        -X POST https://metric-api.newrelic.com/metric/v1 \
        --data '[{ 
            "metrics":[{ 
                "name":"memory.heap", 
                "type":"gauge", 
                "value":2.3, 
                "timestamp":CURRENT_TIME, 
                "attributes":{"host.name":"dev.server.com"} 
            }] 
        }]'


 