name: Retrieve Github Repository Events

on:
  push:
    branches:
      - main

env:
  OWNER: ihappysoni
  REPO: https://github.com/ihappysoni/BlogAppNode
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  retrieve-events:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Retrieve Github Repository Events
      run: |
        const axios = require('axios');

        const url = `https://api.github.com/repos/${process.env.OWNER}/${process.env.REPO}/events`;

        axios.get(url, {
          headers: {
            Authorization: `Token ${process.env.TOKEN}`
          }
        })
        .then(response => {
          console.log("Events retrieved:", response.data);
        })
        .catch(error => {
          console.error("Request failed with error:", error);
        });
