name: Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  newrelic:
    runs-on: ubuntu-latest
    steps:
    - name: Send Deployment Event to New Relic Insights
      run: |
        curl -X POST "https://insights-collector.newrelic.com/v1/accounts/3660048/events" \
        -H "Content-Type: application/json" \
        -H "X-Insert-Key: 5dc59a37501da129d314f363a52804fc17eeNRAL" \
        -d '{
              "eventType": "Deployment",
              "deployment": {
              "repo": "${{ github.repository }}",
              "commitSha": "${{ github.sha }}",
              "commitMessage": "${{ github.event.head_commit.message }}",
              "ref": "${{ github.ref }}"
              }
            }'